"""changed the relation bt parent and guardian table

Revision ID: 1db24eaa07b3
Revises: 5fb7ef09ad18
Create Date: 2026-08-18 18:33:44.402594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db24eaa07b3'
down_revision: Union[str, Sequence[str], None] = '5fb7ef09ad18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
