"""added guardian table and parent guardian relation

Revision ID: 5fb7ef09ad18
Revises: ace80deef2b9
Create Date: 2026-08-18 18:23:17.602104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb7ef09ad18'
down_revision: Union[str, Sequence[str], None] = 'ace80deef2b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
