"""add expires_at to refresh_tokken

Revision ID: 8bf38229660d
Revises: 3e6d06a348d0
Create Date: 2026-08-20 18:59:51.525056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf38229660d'
down_revision: Union[str, Sequence[str], None] = '3e6d06a348d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokken', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('refresh_tokken', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('refresh_tokken_user_id_fkey'), 'refresh_tokken', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokken', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokken', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokken_user_id_fkey'), 'refresh_tokken', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.alter_column('refresh_tokken', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('refresh_tokken', 'expires_at')
    # ### end Alembic commands ###
