"""Add permissions relationship to role

Revision ID: e2cdd3e372a3
Revises: cc0aeddec18d
Create Date: 2026-08-20 13:55:58.370703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2cdd3e372a3'
down_revision: Union[str, Sequence[str], None] = 'cc0aeddec18d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokken', 'user_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('role', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(op.f('role_permissions_role_id_fkey'), 'role_permissions', type_='foreignkey')
    op.drop_constraint(op.f('role_permissions_permission_id_fkey'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['permission_id'])
    op.create_foreign_key(None, 'role_permissions', 'role', ['role_id'], ['role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('role_permissions_permission_id_fkey'), 'role_permissions', 'permissions', ['permission_id'], ['permission_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('role_permissions_role_id_fkey'), 'role_permissions', 'role', ['role_id'], ['role_id'], ondelete='CASCADE')
    op.alter_column('role', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('refresh_tokken', 'user_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
