"""make_user_id_nullable_in_messages

Revision ID: 3193164b40a1
Revises: 644a4bb3019e
Create Date: 2026-06-21 16:41:58.197930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3193164b40a1'
down_revision: Union[str, Sequence[str], None] = '644a4bb3019e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
