"""nullable = False -> True

Revision ID: a1961bc2b354
Revises: 3931148407bf
Create Date: 2026-06-17 01:46:28.455737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1961bc2b354'
down_revision: Union[str, Sequence[str], None] = '3931148407bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'location',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'date_birth',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'date_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('users', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'location',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
